name: ffmpeg_win32_with_fdk_aac

on:
#  push:
#    branches: 
#      - master
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  job1:
    name: job1
    runs-on: ubuntu-20.04
    env: 
      VERSION: master
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare environment
      run: |
        cd $HOME
        git clone https://github.com/rdp/ffmpeg-windows-build-helpers.git
        sudo apt update
        sudo apt install subversion ragel curl texinfo g++ ed bison flex cvs yasm automake libtool autoconf gcc cmake git make pkg-config zlib1g-dev unzip pax nasm gperf autogen bzip2 autoconf-archive p7zip-full meson clang python3-distutils python-is-python3 -y
    - name: Build
      run: |
        cd $HOME/ffmpeg-windows-build-helpers
        rm -rf sandbox
        bash ./cross_compile_ffmpeg.sh --ffmpeg-git-checkout-version=$VERSION --disable-nonfree=n --compiler-flavors=win32 --build-ffmpeg-static=y --build-ffmpeg-shared=n
    - name: Create compressed file
      run: |
        cd $HOME
        7za a ffmpeg_win32_with_fdk_aac.7z $HOME/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_with_fdk_aac_$VERSION/ffmpeg.exe $HOME/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_with_fdk_aac_$VERSION/ffprobe.exe $HOME/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_with_fdk_aac_$VERSION/ffplay.exe -mx=9
    - name: Create compressed file
      run: |
        cd $HOME
        7za a ffmpeg_win32_with_fdk_aac_g.7z $HOME/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_with_fdk_aac_$VERSION/ffmpeg_g.exe $HOME/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_with_fdk_aac_$VERSION/ffprobe_g.exe $HOME/ffmpeg-windows-build-helpers/sandbox/win32/ffmpeg_git_with_fdk_aac_$VERSION/ffplay_g.exe -mx=9
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg_win32_with_fdk_aac
        path: ~/ffmpeg_win32_with_fdk_aac.7z
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: ffmpeg_win32_with_fdk_aac
        path: ~/ffmpeg_win32_with_fdk_aac_g.7z
        
